<input id="nav-trigger" type="checkbox" hidden>
<div class="header">
  <label for="nav-trigger" class="nav-trigger">
    <img src="burger-icon.svg" class="burger-icon">
  </label>
  <a href="index.html">
    <img src="asm-logo.svg" class="asm-icon">
  </a>
  <span class="asm-title">ASM</span>
  <a href="https://gitlab.ow2.org/asm/asm">
    <img src="gitlab-logo.svg" class="gitlab-icon">
  </a>
</div>
<label for="nav-trigger" class="nav-overlay"></label>
<nav>
  <ul>
    <li><a href="index.html">Home</a></li>
    <li>
      <a href="documentation.html">Documentation</a>
      <ul>
        <li><a href="asm4-guide.pdf">User guide</a></li>
        <li><a href="javadoc/overview-summary.html">Javadoc</a></li>
        <li><a href="faq.html">FAQ</a></li>
        <li><a href="developer-guide.html">Developer guide</a></li>
      </ul>
    </li>
    <li>
      <a href="about.html">About</a>
      <ul>
        <li><a href="license.html">License</a></li>
        <li><a href="publications.html">Publications</a></li>
        <li><a href="versions.html">Versions</a></li>
      </ul>
    </li>
  </ul>
</nav>
